### ISSUE TITLE
[Feature] Defaults for placeholders

### ISSUE THREAD

**Issue by zweicoder** [tokozedg/sman#1]
Great repo! Would love to be able to have defaults for placeholders if possible. Maybe something like `<<name(option1,option2)#Description%default>>` for the syntax

**Comment by tokozedg** [comment]
Hi
Thanks for submitting a feature.

Defaults for placeholder is a good idea, and what I missed to write in Readme is that first option of placeholder is assumed as default input. 

```
~|⇒ s r index:delet -c                                                                                                                                                          
----
curl -XDELETE 'http://[host]/[index]/'
----
[host] [1] localhost:9200: 
[index]: test
----
curl -XDELETE 'http://localhost:9200/test/'
----
Snippet Copied...
~|⇒ 
```

In this case, `[host]` placeholder was filled with option1.

Do you think this meets your expectation?

**Comment by zweicoder** [comment]
Yes it does thanks for responding! Closing this issue now.
