### ISSUE TITLE
Providing platform binaries

### ISSUE THREAD

**Issue by antham** [tokozedg/sman#3]
Hi,
it could be nice to provide binaries for most common platforms, it's easy with gox for instance, lot of people don't have go and don't want  to install it. You would reach a wider audience doing so.

**Comment by tokozedg** [comment]
Hi Antham,
I agree with you. I do plan to make installer script, but at this moment can't dedicate enough time to do progress with this project. After finishing refactoring and tests, I will create binaries for various platforms.

Thanks for suggestion.

**Comment by antham** [comment]
Cool great, thx for your quick response :+1: . Your soft is really nice, thx for that !
