### ISSUE TITLE
Unsure about command options

### ISSUE THREAD

**Issue by obihann** [tokozedg/sman#7]
I'm unsure how | and >- are used on the command line of a snippet file, further documentation would be priceless 😄

**Comment by tokozedg** [comment]
Hi,
Generally if command is single line but long like:

```
GRANT <<priv(all privileges,select,select\,update\,insert\,delete)>> ON <<db>>.* TO <<user>>@'<<ip(%,localhost)>>' IDENTIFIED BY '<<pass>>';
```

according to YML syntax you can use `>-` to split the line but it will still be rendered as single. Minus at the end removes last new line character.

On the other hand you can use `|` to render command as multiline for easier reading:

```
command: |
      go test -coverprofile=cover.out;
      go tool cover -html=cover.out
```

This is kinda personal taste and YML related, you can use any type of line breaks as YML defines.
You can check more details [here](http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines).

**Comment by obihann** [comment]
Thanks, didn't realize it was a YML feature.
